### ISSUE TITLE
docker-compose.yml to add in README.md

### ISSUE THREAD

**Issue by PSF1** [serge-chat/serge#342]
Hi,

Using chatGPT, I transformed the command in https://github.com/nsarrazin/serge#getting-started to Docker Compose.

It's more easy to start and stop it.

docker-compose.yml
```yaml
# Generated by chatGPT by OpenAI from documented docker command in https://github.com/nsarrazin/serge#getting-started
# docker run -d -v weights:/usr/src/app/weights -v datadb:/data/db/ -p 8008:8008 ghcr.io/nsarrazin/serge:latest
version: '3'
services:
  serge:
    image: ghcr.io/nsarrazin/serge:latest
    ports:
      - 8008:8008
    volumes:
      - weights:/usr/src/app/weights
      - datadb:/data/db/
volumes:
  weights:
  datadb:
```

We can start it with `docker-compose up -d` and stop it with `docker-compose down`
